name: "Check continue on error"
on:
  workflow_dispatch:
jobs:
  continue-step:
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      result: ${{ steps.success-step.outputs.result }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "ls -a"
        run: ls -a
      - name: "Upload artifact"
        uses: actions/upload-artifact@v3
        with:
          name: test-upload
          path: test.txt
      - name: "Fail with continue-on-error"
        continue-on-error: true
        run: exit 1
      - name: "Return success"
        id: success-step
        run: |
          step_var=$(( vars.SUCCESS_MESSAGE ))
          echo "Message: $step_var"
          echo "result=dajepo" >> GITHUB_OUTPUT
  continue-job:
    runs-on: ubuntu-latest
    needs: continue-step
    continue-on-error: true
    steps:
      - name: "Get output from needs"
        run: echo ${{ needs.continue-step.outputs.result }}
      - name: "Throw error"
        run: exit 1000
  foo-job:
    runs-on: ubuntu-latest
    needs: continue-job
    steps:
      - name: "Echo something"
        run: echo "$GITHUB_REPOSITORY"
