name: "Reuse workflow from other repository"
on:
  workflow_dispatch:
    inputs:
      name:
jobs:
  use-matrix:
    runs-on: ubuntu-latest
    environment: $ {{ matrix.environment }}
    strategy:
      matrix:
        runs-on: [ubuntu-latest, windows-latest]
        environment: [one, two, three]
        include:
          - var: ${{ vars.VAR }}
          - runs-on: ubuntu-latest
            environment: {}
            var: ${{ vars.VAR }}
        exclude:
          - environment: two
          - environment: three
    steps:
      - name: "Echo var"
        shell: bash
        run: echo ${{ matrix.var }}
  reuse-workflow:
    uses: giulio-ricchelli-porini/GitHubActions-Udemy2-PracticeFree1/.github/workflows/push-workflow_call.yml@main
    with:
      name: ${{ inputs.name }}
