name: "Reuse workflow and action from other repository"
on:
  workflow_dispatch:
    inputs:
      name:
jobs:
  use-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        envir: [one, two, three]
        include:
          - var: ${{ vars.VAR }}
          - runs-on: ubuntu-latest
            environment: {}
            var: ${{ vars.VAR }}
        exclude:
          - environment: two
          - environment: three
    runs-on: ${{ matrix.os }}
    environment: one
    steps:
      - name: "Echo var"
        shell: bash
        run: echo ${{ matrix.var }}
  reuse-workflow:
    uses: giulio-ricchelli-porini/GitHubActions-Udemy2-PracticeFree1/.github/workflows/push-workflow_call.yml@main
    with:
      name: ${{ inputs.name }}
  call-external-action:
    uses: giulio-ricchelli-porini/GitHubActions-Udemy2-PracticeFree1/./.github/actions/composite-action
    with:
      repo-secret: "super-secret"
