name: "Reuse workflow and action from other repositories with matrix"
on:
  workflow_dispatch:
    inputs:
      name:
jobs:
  use-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        envir: [one, two, three]
        include:
          - var: ${{ vars.VAR }}
          - runs-on: ubuntu-latest
            envir: {}
            var: ${{ vars.VAR }}
        exclude:
          - envir: two
          - envir: three
    runs-on: ${{ matrix.os }}
    environment: ${{ matrix.envir }}
    steps:
      - name: "Echo var"
        shell: bash
        run: echo ${{ matrix.var }}
  reuse-workflow:
    uses: giulio-ricchelli-porini/GitHubActions-Udemy2-PracticeFree1/.github/workflows/push-workflow_call.yml@main
    with:
      name: ${{ inputs.name }}
  call-external-action:
    runs-on: ubuntu-latest
    steps:
      - name: "Call external action"
        uses: giulio-ricchelli-porini/GitHubActions-Udemy2-PracticeFree1/.github/actions/composite-action@main
        with:
          repo-secret: "sssuper sssecret"
